### ISSUE TITLE
Use of `- 'on_branch:master=foo:{git_branch}'` on a branch with a `/` breaks builds

### ISSUE THREAD

**Issue by grempe** [CtripCloud/docker-make#18]
If you are on a branch with a `/` in it (as is used in the `git flow` tool), like `feature/foo` and you have docker-make configured to use the `git_branch` tag it fails with an error like:

```
INFO dmake.build(147) 2017-07-08 17:08:25,196 node-base: tag added: REPONAME:latest
ERROR docker-make(91) 2017-07-08 17:08:25,199 failed to build node-base
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/dmake/cli.py", line 86, in _main
    build.tag()
  File "/usr/local/lib/python2.7/site-packages/dmake/build.py", line 112, in tag
    self.docker.tag(self.final_image, repo, tag_name, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/docker/utils/decorators.py", line 19, in wrapped
    return f(self, resource_id, *args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/docker/api/image.py", line 510, in tag
    self._raise_for_status(res)
  File "/usr/local/lib/python2.7/site-packages/docker/api/client.py", line 222, in _raise_for_status
    raise create_api_error_from_http_exception(e)
  File "/usr/local/lib/python2.7/site-packages/docker/errors.py", line 31, in create_api_error_from_http_exception
    raise cls(e, response=response, explanation=explanation)
APIError: 500 Server Error: Internal Server Error ("invalid tag format")
make: *** [test-aggregator] Error 1
```

The build setup for that was:

```
     pushes:
       - 'on_tag=quay.io/chainpoint/bcoin:{git_tag}'
       - 'on_branch:master=REPONAME:latest'
       - 'on_branch:master=REPONAME:{git_branch}'
       - 'on_branch:master=REPONAME:{fcommitid}'
     labels:
       - 'org.chainpoint.git.commitid={fcommitid}'
```

Removing this resolved this issue:

```
       - 'on_branch:master=REPONAME:{git_branch}'
```

**Comment by jizhilong** [comment]
That's definitely a bug of `docker-make`, I'll try to fix it later
